language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit
